const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');

class CodeGenerator {
    constructor(irResults, symbolTable, workbook) {
        this.irNodes = irResults.nodes; // Map<addr, IRNode>
        this.order = irResults.order;
        this.symbolTable = symbolTable;
        this.workbook = workbook;
        this.outputDir = path.join(process.cwd(), 'output');
    }

    generate() {
        if (!fs.existsSync(this.outputDir)) {
            fs.mkdirSync(this.outputDir);
        }

        this.generateHTML();
        this.generateCSS();
        this.generateJS();
        this.generateServer();
        this.generateSQL();
    }

    generateHTML() {
        let html = `<!DOCTYPE html>
<html>
<head>
    <title>Excel2App Generated Application</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Excel2App: ${path.basename(this.outputDir)}</h1>
    </header>
    <main id="app">`;

        for (const sheetName of this.workbook.SheetNames) {
            html += `\n        <section class="sheet-card">
            <h2>${sheetName}</h2>
            <div class="sheet-grid" data-sheet="${sheetName}">`;

            // Filter nodes for this sheet
            const sheetNodes = [...this.irNodes.values()].filter(n => n.cellAddress.startsWith(sheetName + '!') && n.isLive);
            
            // Sort by row then col for correct grid layout
            sheetNodes.sort((a, b) => {
                const ea = this.symbolTable.get(a.cellAddress);
                const eb = this.symbolTable.get(b.cellAddress);
                return ea.row - eb.row || ea.col - eb.col;
            });

            let currentRow = -1;
            for (const node of sheetNodes) {
                const entry = this.symbolTable.get(node.cellAddress);
                const id = node.cellAddress.replace(/!/g, '_').replace(/[\$\:]/g, '');
                
                if (entry.row !== currentRow) {
                    if (currentRow !== -1) html += `\n                </div>`;
                    html += `\n                <div class="row">`;
                    currentRow = entry.row;
                }

                html += `\n                    <div class="cell-wrapper" title="${node.cellAddress}">`;
                html += `\n                        <label>${node.cellAddress.split('!')[1]}</label>`;

                if (entry.tokenType === 'FORMULA') {
                    html += `\n                        <span id="${id}" class="formula-cell">0</span>`;
                } else {
                    const typeAttr = entry.inferredType === 'NUMBER' ? 'type="number"' : 'type="text"';
                    const val = entry.value !== null ? entry.value : '';
                    html += `\n                        <input id="${id}" ${typeAttr} value="${val}" class="input-cell" oninput="recalculate()">`;
                }
                html += `\n                    </div>`;
            }
            if (currentRow !== -1) html += `\n                </div>`;

            html += `\n            </div>
        </section>`;
        }

        html += `\n    </main>
    <script src="app.js"></script>
</body>
</html>`;

        fs.writeFileSync(path.join(this.outputDir, 'index.html'), html);
    }

    generateCSS() {
        const css = `
body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f0f2f5; margin: 0; padding: 20px; }
header { margin-bottom: 20px; color: #1a73e8; }
.sheet-card { background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); padding: 20px; margin-bottom: 30px; }
.sheet-grid { display: flex; flex-direction: column; gap: 10px; }
.row { display: flex; gap: 10px; align-items: flex-end; }
.cell-wrapper { display: flex; flex-direction: column; min-width: 100px; }
.cell-wrapper label { font-size: 10px; color: #888; margin-bottom: 2px; }
.input-cell, .formula-cell { border: 1px solid #ddd; padding: 8px; border-radius: 4px; font-size: 14px; min-height: 20px; display: block; }
.formula-cell { background: #f8f9fa; color: #1a73e8; font-weight: bold; border-color: #1a73e8; }
.error-cell { background: #fff5f5; border-color: #ff4d4d; color: #ff4d4d; }
input:focus { border-color: #1a73e8; outline: none; box-shadow: 0 0 0 2px rgba(26,115,232,0.2); }
`;
        fs.writeFileSync(path.join(this.outputDir, 'style.css'), css);
    }

    generateJS() {
        let js = `/** 
 * Generated by Excel2App Reactive Runtime
 */

function recalculate() {
    console.log('Recalculating...');
    try {
        updateAllValues();
    } catch (e) {
        console.error('Recalculation error:', e);
    }
}

function getCellValue(id) {
    const el = document.getElementById(id);
    if (!el) return null;
    if (el.tagName === 'INPUT') {
        const val = el.value;
        return isNaN(val) || val === '' ? val : Number(val);
    }
    return isNaN(el.innerText) ? el.innerText : Number(el.innerText);
}

function setCellValue(id, val) {
    const el = document.getElementById(id);
    if (!el) return;
    if (typeof val === 'object' && val.error) {
        el.innerText = '#ERROR!';
        el.classList.add('error-cell');
        el.title = val.message;
    } else {
        el.innerText = val;
        el.classList.remove('error-cell');
        el.title = '';
    }
}

// Helper functions for operations
const Ops = {
    SUM: (...args) => args.flat().reduce((a, b) => a + (Number(b) || 0), 0),
    AVERAGE: (...args) => {
        const flat = args.flat();
        return flat.reduce((a, b) => a + (Number(b) || 0), 0) / flat.length;
    },
    IF: (cond, a, b) => cond ? a : b,
    PRODUCT: (...args) => args.flat().reduce((a, b) => a * (Number(b) || 1), 1)
};

`;

        // Emit constants for folded nodes and regular CONST nodes
        for (const [addr, node] of this.irNodes) {
            if (!node.isLive) continue;
            const id = node.cellAddress.replace(/!/g, '_').replace(/[\$\:]/g, '');
            if (node.operation === 'CONST') {
                const val = typeof node.value === 'string' ? `"${node.value}"` : node.value;
                js += `const val_${id} = ${val};\n`;
            }
        }

        js += `\nfunction updateAllValues() {\n`;
        
        for (const addr of this.order) {
            const node = this.irNodes.get(addr);
            if (!node || !node.isLive || node.operation === 'CONST') continue;

            const entry = this.symbolTable.get(addr);
            const id = addr.replace(/!/g, '_').replace(/[\$\:]/g, '');
            
            js += `    // ${addr}\n`;
            if (entry.inferredType === 'ERROR') {
                js += `    const res_${id} = { error: true, type: "CompilerError", message: "Semantic or Syntax error" };\n`;
            } else {
                js += `    const res_${id} = ${this.generateExpression(node)};\n`;
            }
            
            if (entry.tokenType === 'FORMULA') {
                js += `    setCellValue("${id}", res_${id});\n`;
            }
        }
        
        js += `}\n\n// Initial calculate\nupdateAllValues();\n`;

        fs.writeFileSync(path.join(this.outputDir, 'app.js'), js);
    }

    generateExpression(node) {
        if (node.operation === 'CONST') {
            return typeof node.value === 'string' ? `"${node.value}"` : node.value;
        }
        if (node.operation === 'LOAD') {
            const depNode = node.operands[0];
            const depId = depNode.cellAddress.replace(/!/g, '_').replace(/[\$\:]/g, '');
            const entry = this.symbolTable.get(depNode.cellAddress);
            if (entry.tokenType === 'FORMULA') {
                if (depNode.operation === 'CONST') return `val_${depId}`;
                return `res_${depId}`;
            } else {
                return `getCellValue("${depId}")`;
            }
        }
        if (node.operation.startsWith('BINOP:')) {
            const op = node.operation.split(':')[1];
            const l = this.generateExpression(node.operands[0]);
            const r = this.generateExpression(node.operands[1]);
            if (op === '&') return `String(${l}) + String(${r})`;
            if (op === '^') return `Math.pow(${l}, ${r})`;
            if (op === '=') return `(${l} === ${r})`;
            if (op === '<>') return `(${l} !== ${r})`;
            return `(${l} ${op} ${r})`;
        }
        if (node.operation.startsWith('UNOP:')) {
            const op = node.operation.split(':')[1];
            const opnd = this.generateExpression(node.operands[0]);
            if (op === 'NOT') return `!(${opnd})`;
            return `${op}(${opnd})`;
        }
        if (node.operation.startsWith('CALL:')) {
            const name = node.operation.split(':')[1];
            const args = node.operands.map(o => this.generateExpression(o)).join(', ');
            return `Ops.${name}(${args})`;
        }
        return 'null';
    }

    generateServer() {
        const serverJs = `
const express = require('express');
const path = require('path');
const bodyParser = require('body-parser');

const app = express();
const PORT = 3000;

app.use(bodyParser.json());
app.use(express.static(__dirname));

// In-memory store (initialized from CSV/SQL in real apps)
let data = {}; 

app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

app.get('/api/:sheet', (req, res) => {
    const sheet = req.params.sheet;
    const sheetData = Object.keys(data)
        .filter(k => k.startsWith(sheet + '!'))
        .reduce((obj, key) => {
            obj[key] = data[key];
            return obj;
        }, {});
    res.json(sheetData);
});

app.post('/api/cell', (req, res) => {
    const { address, value, type } = req.body;
    console.log(\`Updating \${address} to \${value}\`);
    // Basic validation
    if (type === 'NUMBER' && isNaN(value)) {
        return res.status(400).json({ error: 'Type mismatch' });
    }
    data[address] = value;
    res.json({ success: true });
});

app.listen(PORT, () => {
    console.log(\`Server running at http://localhost:\${PORT}\`);
});
`;
        fs.writeFileSync(path.join(this.outputDir, 'server.js'), serverJs);
    }

    generateSQL() {
        let sql = `-- Generated SQLite Schema for Excel2App\n\n`;
        
        for (const sheetName of this.workbook.SheetNames) {
            const sheet = this.workbook.Sheets[sheetName];
            const range = XLSX.utils.decode_range(sheet['!ref'] || 'A1:A1');
            
            // Collect used columns
            const cols = [];
            for (let C = range.s.c; C <= range.e.c; ++C) {
                const colName = XLSX.utils.encode_col(C);
                // Peek first row for header or just use Col A, B...
                cols.push(colName);
            }

            const cleanSheetName = sheetName.replace(/\s+/g, '_');
            sql += `CREATE TABLE IF NOT EXISTS ${cleanSheetName} (\n`;
            sql += `    row_id INTEGER PRIMARY KEY,\n`;
            
            const colDefs = cols.map(c => {
                // Find first non-empty cell in this column to get type
                let type = 'TEXT';
                for (let R = range.s.r; R <= range.e.r; ++R) {
                    const addr = `${sheetName}!${c}${R+1}`;
                    const entry = this.symbolTable.get(addr);
                    if (entry) {
                        switch (entry.inferredType) {
                            case 'NUMBER': type = 'REAL'; break;
                            case 'BOOLEAN': type = 'INTEGER'; break;
                            case 'STRING': type = 'TEXT'; break;
                        }
                        break;
                    }
                }
                return `    ${c} ${type}`;
            });
            
            sql += colDefs.join(',\n');
            sql += `\n);\n\n`;

            // Insert initial values (only constants)
            for (let R = range.s.r; R <= range.e.r; ++R) {
                const rowVals = [];
                const rowCols = [];
                for (let C = range.s.c; C <= range.e.c; ++C) {
                    const cellAddr = XLSX.utils.encode_cell({ r: R, c: C });
                    const fullAddr = `${sheetName}!${cellAddr}`;
                    const entry = this.symbolTable.get(fullAddr);
                    if (entry && entry.tokenType !== 'FORMULA' && entry.value !== null) {
                        rowCols.push(XLSX.utils.encode_col(C));
                        const val = typeof entry.value === 'string' ? `'${entry.value.replace(/'/g, "''")}'` : entry.value;
                        rowVals.push(val);
                    }
                }
                if (rowVals.length > 0) {
                    sql += `INSERT INTO ${cleanSheetName} (row_id, ${rowCols.join(', ')}) VALUES (${R+1}, ${rowVals.join(', ')});\n`;
                }
            }
            sql += `\n`;
        }

        fs.writeFileSync(path.join(this.outputDir, 'schema.sql'), sql);
    }
}

module.exports = { CodeGenerator };
